manifest:
  remotes:
    - name: voidyourwarranty
      url-base: https://gitlab.com/voidyourwarranty
      */  projects:
    - name: zmk-yackboard-3.2
      remote: voidyourwarranty
      revision: devel-pim447
      import: app/west.yml
  self:
    path: config