manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: heyjva
      url-base: https://github.com/heyjva
    - name: petejohanson
      url-base: https://github.com/petejohanson
  projects:
    - name: zmk-view-trackpad
      remote: heyjva
      revision: feat/pointers-move-scroll
      import: app/west.yml
    - name: cirque-input-module
      remote: petejohanson
      revision: main
  self:
    path: config